using Microsoft.JSInterop;

namespace OnceDeOro.Services;

/// <summary>
/// Localización simple: la CLAVE es el texto en español. Para inglés/portugués se
/// busca en el diccionario; si falta, cae al español. Idioma persistido en localStorage.
/// </summary>
public sealed class Loc
{
    private const string Key = "once-de-oro:lang:v1";
    private readonly IJSRuntime _js;
    public Loc(IJSRuntime js) => _js = js;

    public string Lang { get; private set; } = "es";
    public event Action? Changed;

    /// <summary>
    /// Idiomas disponibles. Se muestra el CÓDIGO (ES/EN/PT) y no un emoji de bandera
    /// porque Windows no dibuja las banderas: se veían como letras sueltas ilegibles.
    /// </summary>
    public static readonly (string Code, string Label, string Name)[] Languages =
    {
        ("es", "ES", "Español"),
        ("en", "EN", "English"),
        ("pt", "PT", "Português"),
    };

    public async Task LoadAsync()
    {
        try
        {
            var v = await _js.InvokeAsync<string?>("localStorage.getItem", Key);
            if (v is "es" or "en" or "pt") Lang = v;
        }
        catch { }
        Changed?.Invoke();
    }

    public async Task SetLangAsync(string lang)
    {
        if (lang is not ("es" or "en" or "pt") || lang == Lang) return;
        Lang = lang;
        try { await _js.InvokeVoidAsync("localStorage.setItem", Key, lang); } catch { }
        Changed?.Invoke();
    }

    /// <summary>Traduce (clave = español). Uso: Loc.T("Mercado de fichajes").</summary>
    public string T(string es)
    {
        if (Lang == "es") return es;
        var dict = Lang == "en" ? En : Pt;
        return dict.TryGetValue(es, out var v) ? v : es;
    }

    // Índice cómodo: @Loc["texto"]
    public string this[string es] => T(es);

    private static readonly Dictionary<string, string> En = new()
    {
        // Navegación / topbar
        ["Inicio"] = "Home",
        ["Mercado"] = "Market",
        ["Equipo"] = "Squad",
        ["Torneos"] = "Cups",
        ["Online"] = "Online",
        ["Once de Oro · Manager"] = "Once de Oro · Manager",
        ["Presupuesto disponible"] = "Available budget",
        ["Idioma"] = "Language",
        // Home
        ["★ Temporada abierta"] = "★ Season open",
        ["Empezás de cero con tu presupuesto. Fichá leyendas de todos los Mundiales, ganá torneos, cobrá premios y volvé al mercado por más estrellas. La meta legendaria: ser campeón sin recibir un solo gol."]
            = "Start from scratch with your budget. Sign legends from every World Cup, win cups, collect prizes and return to the market for more stars. The legendary goal: be champion without conceding a single goal.",
        ["▶ Continuar torneo"] = "▶ Continue cup",
        ["🏆 Inscribirse a un torneo"] = "🏆 Enter a cup",
        ["💰 Ir al mercado de fichajes"] = "💰 Go to the transfer market",
        ["👕 Ver mi equipo"] = "👕 View my squad",
        ["Estado del club"] = "Club status",
        ["Fuerza del equipo"] = "Team strength",
        ["XI TITULAR COMPLETO"] = "FULL STARTING XI",
        ["DE CANTERA"] = "YOUTH",
        ["Palmarés"] = "Honours",
        ["Todavía sin trofeos."] = "No trophies yet.",
        ["¡Salí a ganar tu primer título!"] = "Go win your first title!",
        ["⭐ CAMPEÓN INVICTO SIN RECIBIR GOLES"] = "⭐ UNBEATEN CHAMPION, NO GOALS CONCEDED",
        ["Carrera"] = "Career",
        ["Partidos"] = "Matches",
        ["Ganados"] = "Won",
        ["Empates"] = "Draws",
        ["Perdidos"] = "Lost",
        ["Goles a favor"] = "Goals for",
        ["En contra"] = "Against",
        ["Historial de torneos"] = "Cup history",
        ["↺ Reiniciar carrera"] = "↺ Reset career",
        ["jugadores"] = "players",
        // Mercado
        ["Mercado de fichajes"] = "Transfer market",
        ["💰 Comprar"] = "💰 Buy",
        ["👕 Mi plantel"] = "👕 My squad",
        ["Todos"] = "All",
        ["🔎 Buscar jugador o selección…"] = "🔎 Search player or country…",
        ["🌍 Todos los países"] = "🌍 All countries",
        ["📅 Todas las épocas"] = "📅 All eras",
        ["✕ Limpiar"] = "✕ Clear",
        ["No hay jugadores con ese filtro."] = "No players match that filter.",
        ["Tu plantel está vacío. Andá a Comprar para fichar."] = "Your squad is empty. Go to Buy to sign players.",
        // Equipo
        ["Mi equipo"] = "My squad",
        ["No tenés jugadores todavía."] = "You don't have any players yet.",
        ["💰 Ir al mercado"] = "💰 Go to the market",
        ["Nombre del club"] = "Club name",
        ["Nombre de tu equipo"] = "Your team name",
        ["Formación"] = "Formation",
        ["Estilo"] = "Style",
        ["Defensivo"] = "Defensive",
        ["Equilibrado"] = "Balanced",
        ["Ofensivo"] = "Attacking",
        ["Fuerza"] = "Strength",
        ["⚡ Auto XI"] = "⚡ Auto XI",
        ["✓ XI TITULAR COMPLETO — LISTO PARA JUGAR"] = "✓ FULL STARTING XI — READY TO PLAY",

        // ---- concentración ----
        ["🛌 Concentración"] = "🛌 Rest camp",
        ["Mandalos a concentrar y en 1 minuto vuelven enteros. Mientras descansan no pueden jugar: ese es el precio."]
            = "Send them to the rest camp and in 1 minute they're back at 100%. While resting they can't play: that's the price.",
        ["😴 Que descansen todos"] = "😴 Rest everyone",
        ["Están todos enteros. A jugar."] = "Everyone's fresh. Go play.",
        ["Descansar"] = "Rest",

        // ---- cajas sorpresa ----
        ["🎁 Cajas"] = "🎁 Boxes",
        ["Caja Básica"] = "Basic Box",
        ["Caja de Plata"] = "Silver Box",
        ["Caja de Oro"] = "Gold Box",
        ["Caja de Leyenda"] = "Legend Box",
        ["Caja Élite"] = "Elite Box",
        ["Piso 90. Acá no hay relleno."] = "90 floor. No filler in here.",
        ["📖 Catálogo"] = "📖 Catalogue",
        ["Todos los jugadores que existen, tengas o no. Los de 100+ son versiones PRIME: no se compran, solo salen de las cajas."]
            = "Every player in the game, owned or not. Tap one to see his full profile.",
        ["Lo tenés"] = "Owned",
        ["Ver más"] = "Show more",
        ["Solo por caja"] = "Box only",
        ["🏟️ Estadio"] = "🏟️ Stadium",
        ["Cuanta más gente entra al estadio, más se recauda en cada partido. La entrada se cobra sola al terminar el partido."] = "The more people fit in the stadium, the more you take at each match. Gate money is collected automatically when the match ends.",
        ["Tu estadio"] = "Your stadium",
        ["por partido"] = "per match",
        ["El tuyo"] = "Yours",
        ["Superado"] = "Outgrown",
        ["Comprar"] = "Buy",
        ["de recaudación"] = "in gate money",
        ["Tribuna Popular"] = "Local Terrace",
        ["La cancha del barrio. Con lo que entra apenas se pagan los focos."] = "The neighbourhood ground. The takings barely cover the floodlights.",
        ["Estadio Municipal"] = "Municipal Stadium",
        ["Tablones de verdad y una popular que empuja."] = "Real stands and a terrace that pushes you on.",
        ["Estadio de Ciudad"] = "City Stadium",
        ["Ya se agotan las entradas una semana antes."] = "Tickets sell out a week in advance.",
        ["Monumental"] = "Monumental",
        ["Tres bandejas. El rival entra intimidado."] = "Three tiers. Visitors walk out intimidated.",
        ["Coloso"] = "Colossus",
        ["De los que salen en la tele del mundo entero."] = "One of those you see on TV worldwide.",
        ["Templo del Fútbol"] = "Temple of Football",
        ["El estadio más grande que se puede tener. Se llena solo."] = "The biggest stadium you can own. It fills itself.",
        ["Suspendido"] = "Suspended",
        ["Suspendido: no puede jugar"] = "Suspended: can't play",
        ["⬆️ Fusiones disponibles"] = "⬆️ Available fusions",
        ["Tenés la versión común de estos jugadores. Sacrificala y su versión prime sube un punto."] = "You own the common version of these players. Sacrifice it and their prime goes up one point.",
        ["Se pierde"] = "You lose",
        ["🎨 Camiseta y estadio"] = "🎨 Kit and stadium",
        ["Colores del club"] = "Club colours",
        ["Principal"] = "Primary",
        ["Secundario"] = "Secondary",
        ["Gradas"] = "Stands",
        ["Clásica"] = "Classic",
        ["Tribuna llena en el color del club."] = "Packed stand in the club colour.",
        ["Bicolor"] = "Two-tone",
        ["Franjas alternadas con los dos colores."] = "Alternating stripes in both colours.",
        ["Mosaico"] = "Mosaic",
        ["El clásico mosaico de la hinchada."] = "The classic supporters mosaic.",
        ["Nocturna"] = "Night",
        ["Estadio a oscuras con celulares prendidos."] = "Dark stadium lit by phone lights.",
        ["Vacía"] = "Empty",
        ["A puertas cerradas, sin público."] = "Behind closed doors, no crowd.",

        // ---- QR, creditos y legales ----
        ["Escaneá para unirte a la sala"] = "Scan to join the room",
        ["Escaneá el QR con el teléfono y entrás directo a la sala."] = "Scan the QR with your phone and you're straight into the room.",
        ["📋 Copiar link"] = "📋 Copy link",
        ["✓ Copiado"] = "✓ Copied",
        ["Creado por"] = "Created by",
        ["Créditos, términos y privacidad"] = "Credits, terms and privacy",
        ["Créditos"] = "Credits",
        ["Juego web tipo manager de fútbol."] = "A football manager web game.",
        ["Creador y desarrollo"] = "Creator and development",
        ["Creador y diseño de juego"] = "Creator and game design",
        ["Los nombres de futbolistas y selecciones son datos históricos de dominio público; las fuerzas y atributos son una valoración propia para el juego y no representan datos oficiales de ninguna liga, club ni federación."] = "Player and national-team names are public-domain historical data; ratings and attributes are our own judgement for the game and do not represent official data from any league, club or federation.",
        ["Términos y condiciones"] = "Terms and conditions",
        ["1. Qué es esto."] = "1. What this is.",
        ["Once de Oro es un juego gratuito, sin fines comerciales y sin dinero real. Toda la moneda del juego es ficticia: no se compra, no se vende y no tiene ningún valor fuera del juego."] = "Once de Oro is a free, non-commercial game with no real money. All in-game currency is fictional: it cannot be bought or sold and has no value outside the game.",
        ["2. Las cajas sorpresa no se pagan."] = "2. Loot boxes are never paid for.",
        ["Las cajas se abren únicamente con moneda del juego que se gana jugando. No existe ninguna forma de comprarlas con dinero real ni de convertir nada del juego en dinero."] = "Boxes are opened only with in-game currency earned by playing. There is no way to buy them with real money or to convert anything in the game into money.",
        ["3. Uso razonable."] = "3. Fair use.",
        ["Pedimos no intentar alterar el juego para perjudicar a otros jugadores en las salas online, ni usar el servicio para enviar contenido ofensivo en los nombres de equipo o de jugador."] = "Please don't tamper with the game to harm other players in online rooms, or use team or player names to send offensive content.",
        ["4. Sin garantías."] = "4. No warranty.",
        ["El juego se ofrece tal como está. Puede tener errores, cambiar o dejar de estar disponible en cualquier momento. No nos hacemos responsables por la pérdida de una partida o de su progreso."] = "The game is provided as is. It may have bugs, change, or stop being available at any time. We are not liable for the loss of a save or its progress.",
        ["5. Licencia del código."] = "5. Code licence.",
        ["El código es público y se distribuye bajo una licencia que permite verlo, aprender de él y compartir mejoras, pero no usarlo con fines comerciales."] = "The code is public under a licence that lets you read it, learn from it and share improvements, but not use it commercially.",
        ["Política de privacidad"] = "Privacy policy",
        ["Qué se guarda en tu dispositivo."] = "What is stored on your device.",
        ["Tu partida (equipo, dinero, torneos y estadísticas) y el idioma elegido se guardan en el almacenamiento local de tu navegador. Si borrás los datos del navegador, esa partida se pierde."] = "Your save (squad, money, cups and stats) and your chosen language are stored in your browser's local storage. If you clear your browser data, that save is gone.",
        ["Qué se guarda en el servidor."] = "What is stored on the server.",
        ["Sólo si te registrás: tu correo, una versión cifrada de tu contraseña (nunca la contraseña en sí) y tu partida, para que puedas seguirla desde otro dispositivo. Nada más."] = "Only if you register: your email, a hashed version of your password (never the password itself) and your save, so you can continue on another device. Nothing else.",
        ["Salas online."] = "Online rooms.",
        ["Mientras jugás una sala se comparte con los demás participantes tu nombre de equipo y los jugadores de tu once. La sala vive en memoria y desaparece cuando todos se van: no queda registro del partido."] = "While you play a room, your team name and starting XI are shared with the other participants. The room lives in memory and disappears when everyone leaves: no record of the match is kept.",
        ["Qué NO hacemos."] = "What we do NOT do.",
        ["No hay publicidad, no hay rastreadores de terceros, no se vende ni se comparte ningún dato con nadie, y no se piden datos de pago porque no hay nada que pagar."] = "No ads, no third-party trackers, no data sold or shared with anyone, and no payment details are ever requested because there is nothing to pay.",
        ["Menores de edad."] = "Minors.",
        ["El juego es apto para todo público y no pide más datos que un correo opcional para guardar la partida."] = "The game is suitable for all ages and asks for no data beyond an optional email to save your progress.",
        ["Borrar tus datos."] = "Deleting your data.",
        ["Podés borrar la partida local desde Inicio con “Reiniciar carrera”. Si te registraste y querés que borremos tu cuenta del servidor, escribinos y la eliminamos."] = "You can delete the local save from Home with “Reset career”. If you registered and want your server account deleted, write to us and we will remove it.",
        ["Contacto:"] = "Contact:",
        ["Tu rival ya fichó a"] = "Your rival already signed",
        ["No pueden jugar los dos con la misma carta, así que tu equipo se armó sin ellos."] = "You can't both field the same card, so your XI was built without them.",
        ["Podés sacrificar a"] = "You can sacrifice",
        ["para que este suba a"] = "to push this one up to",
        ["Mejorar"] = "Upgrade",
        ["Ya lo mejoraste. Se puede una sola vez por jugador."] = "Already upgraded. Once per player.",
        ["Conseguí a"] = "Get",
        ["en el mercado y lo podés sacrificar para subirle un punto a este."] = "in the market and you can sacrifice him to give this one +1.",
        ["Caja Olimpo"] = "Olympus Box",
        ["Sólo dioses: del 100 para arriba, garantizado."] = "Gods only: 100 or above, guaranteed.",
        ["Caja del Payaso"] = "Clown Box",
        ["Casi siempre un relleno. Casi."] = "Almost always a filler. Almost.",
        ["El termino medio: sale un titular decente."] = "Middle ground: a decent starter.",
        ["Acá ya se sueña con una figura."] = "Here you start dreaming of a star.",
        ["Cara como pocas cosas. Y todavía puede salirte un 79."] = "Brutally expensive. And it can still hand you a 79.",
        ["GARANTIZADO: un jugador de 110. Palabra de payaso."] = "GUARANTEED: a 110 player. Clown's honour.",
        ["Abrir"] = "Open",
        ["Listo"] = "Done",
        ["Salió de la caja"] = "Out of the box",
        ["¡GARANTIZADO!"] = "GUARANTEED!",
        ["¡SE ROMPIÓ LA CAJA!"] = "THE BOX BROKE!",
        ["Girando…"] = "Spinning…",
        ["¡FUERA DE ESCALA!"] = "OFF THE CHARTS!",
        ["Un 110 de verdad. Lástima que juegue como un 45."] = "A real 110. Shame he plays like a 45.",
        ["Pagás, tirás la moneda y sale lo que sale. Ojo: lo que salga de una caja se revende a precio de saldo, así que no es negocio abrirlas para vender."]
            = "You pay, you roll the dice, you get what you get. Careful: anything out of a box resells for peanuts, so opening them to sell is no business.",
        ["Cotiza 110 y remata como nadie, pero adentro de la cancha rinde como un 45. Te vendieron humo."]
            = "Valued at 110 and shoots like nobody else, but on the pitch he performs like a 45. You got sold smoke.",
        ["Plantel"] = "Squad",
        ["de cantera cubren los huecos — igual podés jugar"] = "youth players cover the gaps — you can still play",
        ["tocá para poner/sacar del XI"] = "tap to add/remove from the XI",
        ["Cantera"] = "Youth",
        ["libre"] = "free",
        // Torneos
        ["Competiciones"] = "Competitions",
        ["Torneo en curso"] = "Cup in progress",
        ["▶ Continuar"] = "▶ Continue",
        ["Inscribirse"] = "Enter",
        ["Gratis"] = "Free",
        ["Tu fuerza"] = "Your strength",
        ["Premio campeón"] = "Champion prize",
        ["Inscripción"] = "Entry fee",
        ["Nivel"] = "Tier",
        ["⚠️ Necesitás un XI válido (11 titulares según tu formación) para inscribirte."] = "⚠️ You need a valid XI (11 starters for your formation) to enter.",
        ["Armar equipo"] = "Build squad",
        ["Ir al mercado"] = "Go to the market",
        ["Rec."] = "Rec.",
        ["Tu XI tiene juveniles de cantera cubriendo huecos. Podés competir igual, pero fichá refuerzos para rendir mejor."]
            = "Your XI has youth players filling the gaps. You can still compete, but sign reinforcements to perform better.",
        ["Tu equipo está por debajo del nivel — ganá plata en torneos menores y reforzá antes."]
            = "Your team is below the level — earn money in smaller cups and reinforce first.",
        // Torneos: nombres, subtítulos y rondas
        ["Copa Regional"] = "Regional Cup",
        ["Copa América"] = "Copa América",
        ["Champions League"] = "Champions League",
        ["Copa del Mundo"] = "World Cup",
        ["El primer trofeo · rivales accesibles"] = "Your first trophy · reachable rivals",
        ["El continente sudamericano en juego"] = "The South American continent at stake",
        ["La élite europea bajo las luces"] = "Europe's elite under the lights",
        ["La cima · aquí se forja el 7–0 perfecto"] = "The summit · here the perfect 7–0 is forged",
        ["Fase de grupos · Jornada {0}"] = "Group stage · Matchday {0}",
        ["Fecha {0} de {1}"] = "Matchday {0} of {1}",
        ["Ligas nacionales"] = "National leagues",
        ["Copas nacionales"] = "National cups",
        ["Torneos continentales"] = "Continental cups",
        ["Selecciones"] = "National teams",
        ["Liga · todos contra todos"] = "League · round robin",
        ["Eliminación directa"] = "Knockout",
        ["Grupos + eliminatorias"] = "Groups + knockout",
        ["Tabla de posiciones"] = "League table",
        ["Temporada terminada"] = "Season finished",
        ["Fichado"] = "Taken",
        ["Carrera real"] = "Real career",
        ["Partidos con su selección"] = "Caps",
        ["Goles con su selección"] = "International goals",
        ["Mundiales"] = "World Cups",
        ["Balón de Oro"] = "Ballon d'Or",
        ["Copas de Europa"] = "European Cups",
        ["Campeón del Mundo en"] = "World champion in",
        ["finales perdidas"] = "finals lost",
        ["Cualidades dentro del juego, derivadas de su fuerza."] = "In-game qualities, derived from his rating.",
        ["Atributos"] = "Attributes",
        ["No está en tu equipo. Fichalo para verlo rendir y llevarle las estadísticas."]
            = "He's not in your squad. Sign him to see him perform and track his stats.",
        ["Reflejos"] = "Reflexes",
        ["Achique"] = "Rushing out",
        ["Manos"] = "Handling",
        ["Juego aéreo"] = "Aerial",
        ["Distribución"] = "Distribution",
        ["Marca"] = "Marking",
        ["Quite"] = "Tackling",
        ["Fuerza"] = "Strength",
        ["Salida"] = "Build-up",
        ["Pase"] = "Passing",
        ["Visión"] = "Vision",
        ["Regate"] = "Dribbling",
        ["Resistencia"] = "Stamina",
        ["Recuperación"] = "Ball winning",
        ["Definición"] = "Finishing",
        ["Velocidad"] = "Pace",
        ["Remate"] = "Shooting",
        ["Desmarque"] = "Movement",
        ["Época"] = "Era",
        ["Estado físico"] = "Condition",
        ["Lesionado"] = "Injured",
        ["Lesionado: no puede jugar"] = "Injured: can't play",
        ["Sacar del XI"] = "Remove from XI",
        ["Poner en el XI"] = "Add to XI",
        ["Disponible"] = "Available",
        ["partido"] = "match",
        ["partidos"] = "matches",
        ["Cansancio"] = "Fatigue",
        ["de fuerza"] = "strength",
        ["Descansa cuando no juega. Jugar fundido aumenta el riesgo de lesión."]
            = "He rests when he doesn't play. Playing exhausted raises the injury risk.",
        ["Con tu equipo"] = "With your team",
        ["Goles"] = "Goals",
        ["Lesiones"] = "Injuries",
        ["Goles/partido"] = "Goals/match",
        ["Copa juvenil"] = "Youth cup",
        ["Sonido"] = "Sound",
        ["Torneos de formación para tu cantera: cuestan plata y NO dan premio. Lo que ganás es experiencia. No cansan ni lesionan."] = "Development tournaments for your youth players: they cost money and pay NO prize. What you earn is experience. No fatigue, no injuries.",
        ["por jugar"] = "just for playing",
        ["a cada juvenil"] = "to each youth player",
        ["Necesitás al menos 5 juveniles. Creá jugadores o fichá promesas con un ojeador."] = "You need at least 5 youth players. Create some or sign prospects with a scout.",
        ["Elegí 5 juveniles"] = "Pick 5 youth players",
        ["Rival"] = "Rival",
        ["por victoria"] = "per win",
        ["Jugar"] = "Play",
        ["Jugar · Gratis"] = "Play · Free",
        ["ganados"] = "won",
        ["¡INVICTOS!"] = "UNBEATEN!",
        ["Tu cantera"] = "Your youth team",
        ["Copa Barrial"] = "Neighbourhood Cup",
        ["Torneo Sub-19"] = "U-19 Tournament",
        ["Copa Federal Juvenil"] = "National Youth Cup",
        ["Mundialito Juvenil"] = "Youth World Cup",
        ["Potreros del barrio. Entrada libre, ideal para empezar."] = "Local dirt pitches. Free entry, perfect to start.",
        ["Categorías juveniles federadas. Ya se juega en serio."] = "Registered youth categories. Now it gets serious.",
        ["Lo mejor de las inferiores del país."] = "The best youth sides in the country.",
        ["El torneo donde se miran todos los ojeadores del mundo."] = "The tournament every scout in the world watches.",
        ["Ojeadores"] = "Scouts",
        ["Techo"] = "Ceiling",
        ["Mejoras"] = "Upgrades",
        ["Contratar un ojeador"] = "Hire a scout",
        ["Los ojeadores buscan jóvenes promesas. Lo que pagás no es lo que rinden hoy, sino hasta dónde pueden llegar."] = "Scouts look for young prospects. You are not paying for what they are today, but for how far they can go.",
        ["Techo de las promesas"] = "Prospect ceiling",
        ["Buscar"] = "Search",
        ["Todavía no encontraste promesas. Contratá un ojeador."] = "No prospects yet. Hire a scout.",
        ["Promesas encontradas"] = "Prospects found",
        ["años"] = "years old",
        ["Hoy"] = "Today",
        ["Puede llegar a"] = "Can reach",
        ["Fichar"] = "Sign",
        ["Ojeador local"] = "Local scout",
        ["Ojeador regional"] = "Regional scout",
        ["Ojeador internacional"] = "International scout",
        ["Ojeador de élite"] = "Elite scout",
        ["Recorre canchas de barrio. Encuentra chicos aprovechables."] = "Works local pitches. Finds usable kids.",
        ["Cubre todo el país. Aparecen los primeros nombres serios."] = "Covers the whole country. First serious names appear.",
        ["Viaja por el continente. Promesas de selección juvenil."] = "Travels the continent. Youth international prospects.",
        ["La red que descubre a los cracks antes que nadie."] = "The network that finds superstars before anyone else.",
        ["Tokens de mejora"] = "Upgrade tokens",
        ["Sirven para subir de nivel a cualquier jugador tuyo, hasta 99."] = "Use them to level up any of your players, up to 99.",
        ["Cuanto más fuerte es el jugador, más tokens cuesta cada punto. Así mejorar a una estrella es una inversión de verdad."] = "The stronger the player, the more tokens each point costs. Upgrading a star is a real investment.",
        ["Academia"] = "Academy",
        ["Creá tus propios jugadores y hacelos crecer entrenando y jugando. Entrenar cuesta cada vez más caro: es donde tu fortuna encuentra destino."]
            = "Create your own players and grow them by training and playing. Training gets pricier every level: that's where your fortune finally has somewhere to go.",
        ["Nombre"] = "Name",
        ["Tu joya"] = "Your gem",
        ["País"] = "Country",
        ["Puesto"] = "Position",
        ["Costo"] = "Cost",
        ["arranca en"] = "starts at",
        ["＋ Crear jugador"] = "＋ Create player",
        ["No te alcanza la plata para crear un jugador."] = "You don't have enough money to create a player.",
        ["Todavía no creaste ningún jugador."] = "You haven't created any players yet.",
        ["Tus jugadores"] = "Your players",
        ["Entrenar"] = "Train",
        ["Vender"] = "Sell",
        ["Máximo"] = "Maxed",
        ["entrenos"] = "sessions",
        ["Ruta de avances"] = "Progression path",
        ["Rivales"] = "Rivals",
        ["Los rivales se refuerzan con tu trayectoria y tu nivel"] = "Rivals get stronger with your track record and your level",
        ["Juvenil"] = "Youth",
        ["Promesa"] = "Prospect",
        ["Titular"] = "Starter",
        ["Figura"] = "Star",
        ["Crack"] = "Superstar",
        ["Leyenda"] = "Legend",

        ["Liga Argentina"] = "Argentine League",
        ["Premier League"] = "Premier League",
        ["La Liga"] = "La Liga",
        ["Brasileirão"] = "Brasileirão",
        ["Copa Argentina"] = "Copa Argentina",
        ["Copa del Rey"] = "Copa del Rey",
        ["FA Cup"] = "FA Cup",
        ["Copa Libertadores"] = "Copa Libertadores",
        ["Europa League"] = "Europa League",
        ["Eurocopa"] = "Euros",
        ["Temporada completa en el fútbol argentino"] = "A full season in Argentine football",
        ["El campeonato más físico de Sudamérica"] = "South America's most physical championship",
        ["Técnica y posesión al máximo nivel"] = "Technique and possession at the highest level",
        ["La liga más competitiva del mundo"] = "The most competitive league in the world",
        ["Eliminación directa: no se perdona nada"] = "Straight knockout: no second chances",
        ["El torneo de las sorpresas"] = "The cup of upsets",
        ["La copa más antigua del fútbol"] = "Football's oldest cup",
        ["La gloria eterna de Sudamérica"] = "South America's eternal glory",
        ["El camino alternativo a la gloria europea"] = "The alternative road to European glory",
        ["El torneo de selecciones más parejo"] = "The most even national-team tournament",
        ["OCTAVOS DE FINAL"] = "ROUND OF 16",
        ["CUARTOS DE FINAL"] = "QUARTER-FINALS",
        ["SEMIFINAL"] = "SEMI-FINAL",
        ["LA FINAL"] = "THE FINAL",
        // Partido
        ["No hay ningún torneo en curso."] = "There is no cup in progress.",
        ["Elegir torneo"] = "Choose a cup",
        ["PREVIA"] = "PREVIEW",
        ["📊 Pronóstico"] = "📊 Prediction",
        ["goles esperados"] = "expected goals",
        ["favoritismo"] = "favourite",
        ["Marcadores más probables:"] = "Most likely scores:",
        ["Ganás"] = "Win",
        ["Perdés"] = "Lose",
        ["Empate"] = "Draw",
        ["▶ Ver el partido"] = "▶ Watch the match",
        ["FINAL"] = "FULL TIME",
        ["PENALES"] = "PENALTIES",
        ["Recorrido en la"] = "Your run in the",
        ["¡VICTORIA!"] = "WIN!",
        ["EMPATE"] = "DRAW",
        ["DERROTA"] = "DEFEAT",
        ["en premios"] = "in prizes",
        ["¡CAMPEÓN!"] = "CHAMPION!",
        ["Cobrar y volver"] = "Collect and return",
        ["Volver al mercado"] = "Back to the market",
        ["Volver"] = "Back",
        ["Reforzá el equipo y volvé más fuerte."] = "Reinforce your squad and come back stronger.",
        // MatchField
        ["Posesión"] = "Possession",
        ["Remates"] = "Shots",
        ["Faltas"] = "Fouls",
        ["⏩ Saltar al final"] = "⏩ Skip to the end",
        ["1º TIEMPO"] = "1ST HALF",
        ["ENTRETIEMPO"] = "HALF TIME",
        ["2º TIEMPO"] = "2ND HALF",
        ["PRÓRROGA 1"] = "EXTRA TIME 1",
        ["PRÓRROGA 2"] = "EXTRA TIME 2",
        ["TANDA DE PENALES"] = "PENALTY SHOOTOUT",
        // Relato del partido (plantillas con {0}/{1} = nombres/equipo, no se traducen)
        ["¡Comienza el partido!"] = "The match kicks off!",
        ["Falta de {0} sobre {1}"] = "Foul by {0} on {1}",
        ["Amarilla a {0}"] = "Yellow card for {0}",
        ["Roja a {0}"] = "Red card for {0}",
        ["{0} queda golpeado y necesita atención"] = "{0} is down and needs treatment",
        ["Offside · posición adelantada de {0}"] = "Offside · {0} was ahead of play",
        ["Remate de {0} ({1})"] = "Shot by {0} ({1})",
        ["¡GOOOL de {0}!"] = "GOAAAL by {0}!",
        ["¡Atajó {0}!"] = "{0} saves it!",
        ["¡{0} al palo!"] = "{0} hits the post!",
        ["Remate desviado de {0}"] = "{0} shoots wide",
        ["Pausa de hidratación (min {0})"] = "Hydration break (min {0})",
        ["Entretiempo"] = "Half time",
        ["Arranca el segundo tiempo"] = "The second half is under way",
        ["Final del partido"] = "Full time",
        ["¡Tiempo suplementario!"] = "Extra time!",
        ["¡Definición por penales!"] = "It's going to penalties!",
        ["{0} anota"] = "{0} scores",
        ["{0} le ataja a {1}"] = "{0} saves from {1}",
        // Online
        ["Duelo online · jugá contra amigos"] = "Online duel · play against friends",
        ["Crear una sala"] = "Create a room",
        ["Unirse a una sala"] = "Join a room",
        ["Tu nombre"] = "Your name",
        ["Tu apodo"] = "Your nickname",
        ["Equipos"] = "Teams",
        ["Draft parejo"] = "Fair draft",
        ["Equipo de carrera"] = "Career squad",
        ["Formato"] = "Format",
        ["Único"] = "Single",
        ["Mejor de 3"] = "Best of 3",
        ["Mini-torneo"] = "Mini-cup",
        ["🌐 Crear sala"] = "🌐 Create room",
        ["Código de sala"] = "Room code",
        ["Entrar"] = "Join",
        ["Jugadores"] = "Players",
        ["Presupuesto por jugador:"] = "Budget per player:",
        ["Pedile el código de 4 letras a tu amigo que creó la sala."] = "Ask your friend who created the room for the 4-letter code.",
        ["TÚ"] = "YOU",
        ["👑 Anfitrión"] = "👑 Host",
        ["Invitado"] = "Guest",
        ["▶ Empezar"] = "▶ Start",
        ["Esperando que se una al menos un amigo…"] = "Waiting for at least one friend to join with the code",
        ["Esperando que el anfitrión inicie la partida…"] = "Waiting for the host to start the match…",
        ["¡Equipo listo!"] = "Squad ready!",
        ["Esperando al resto…"] = "Waiting for the others…",
        ["(vos)"] = "(you)",
        ["LISTO ✓"] = "READY ✓",
        ["armando…"] = "building…",
        ["Tu equipo de carrera"] = "Your career squad",
        ["✓ Usar este equipo y estar listo"] = "✓ Use this squad and get ready",
        ["Serie:"] = "Series:",
        ["¡GANASTE!"] = "YOU WIN!",
        ["PERDISTE"] = "YOU LOSE",
        ["gana"] = "wins",
        ["gana la contienda online."] = "wins the online contest.",
        ["MINUTO"] = "MINUTE",
        ["Partido"] = "Match",
        ["Partido único"] = "Single match",
        ["Página no encontrada"] = "Page not found",
        ["FUERA DE JUEGO"] = "OFFSIDE",
        ["La página que buscás no existe."] = "The page you're looking for doesn't exist.",
        ["Volver al inicio"] = "Back home",
        // Cuenta
        ["Tu cuenta"] = "Your account",
        ["Guardar progreso"] = "Save progress",
        ["Guardá tu progreso"] = "Save your progress",
        ["Este servidor todavía no tiene cuentas habilitadas. Tu progreso se guarda en este navegador."]
            = "This server doesn't have accounts enabled yet. Your progress is saved in this browser.",
        ["☁ Progreso guardado"] = "☁ Progress saved",
        ["Tu equipo, tu dinero, los torneos y todas tus estadísticas se guardan en tu cuenta y te siguen a cualquier dispositivo."]
            = "Your squad, money, cups and all your stats are stored in your account and follow you to any device.",
        ["☁ Guardar ahora"] = "☁ Save now",
        ["✓ Guardado"] = "✓ Saved",
        ["Cerrar sesión"] = "Log out",
        ["Crear cuenta"] = "Create account",
        ["Creá tu cuenta y todo lo que ya jugaste (equipo, dinero, torneos y estadísticas) se guarda ahí mismo. No perdés nada."]
            = "Create your account and everything you've already played (squad, money, cups and stats) is saved right there. You lose nothing.",
        ["Entrá para recuperar tu equipo y seguir donde lo dejaste."] = "Log in to get your squad back and pick up where you left off.",
        ["Nombre de manager"] = "Manager name",
        ["Email"] = "Email",
        ["Contraseña"] = "Password",
        ["Mínimo 6 caracteres"] = "At least 6 characters",
        ["Un momento…"] = "One moment…",
        ["Crear cuenta y guardar mi progreso"] = "Create account and save my progress",
    };

    private static readonly Dictionary<string, string> Pt = new()
    {
        ["Inicio"] = "Início",
        ["Mercado"] = "Mercado",
        ["Equipo"] = "Elenco",
        ["Torneos"] = "Torneios",
        ["Online"] = "Online",
        ["Presupuesto disponible"] = "Orçamento disponível",
        ["Idioma"] = "Idioma",
        ["★ Temporada abierta"] = "★ Temporada aberta",
        ["Empezás de cero con tu presupuesto. Fichá leyendas de todos los Mundiales, ganá torneos, cobrá premios y volvé al mercado por más estrellas. La meta legendaria: ser campeón sin recibir un solo gol."]
            = "Comece do zero com seu orçamento. Contrate lendas de todas as Copas, vença torneios, receba prêmios e volte ao mercado por mais estrelas. A meta lendária: ser campeão sem sofrer um único gol.",
        ["▶ Continuar torneo"] = "▶ Continuar torneio",
        ["🏆 Inscribirse a un torneo"] = "🏆 Inscrever-se em um torneio",
        ["💰 Ir al mercado de fichajes"] = "💰 Ir ao mercado de transferências",
        ["👕 Ver mi equipo"] = "👕 Ver meu elenco",
        ["Estado del club"] = "Status do clube",
        ["Fuerza del equipo"] = "Força do time",
        ["XI TITULAR COMPLETO"] = "XI TITULAR COMPLETO",
        ["Palmarés"] = "Títulos",
        ["Todavía sin trofeos."] = "Ainda sem troféus.",
        ["¡Salí a ganar tu primer título!"] = "Vá conquistar seu primeiro título!",
        ["⭐ CAMPEÓN INVICTO SIN RECIBIR GOLES"] = "⭐ CAMPEÃO INVICTO SEM SOFRER GOLS",
        ["Carrera"] = "Carreira",
        ["Partidos"] = "Jogos",
        ["Ganados"] = "Vitórias",
        ["Empates"] = "Empates",
        ["Perdidos"] = "Derrotas",
        ["Goles a favor"] = "Gols pró",
        ["En contra"] = "Contra",
        ["Historial de torneos"] = "Histórico de torneios",
        ["↺ Reiniciar carrera"] = "↺ Reiniciar carreira",
        ["jugadores"] = "jogadores",
        ["Mercado de fichajes"] = "Mercado de transferências",
        ["💰 Comprar"] = "💰 Comprar",
        ["👕 Mi plantel"] = "👕 Meu elenco",
        ["Todos"] = "Todos",
        ["🔎 Buscar jugador o selección…"] = "🔎 Buscar jogador ou seleção…",
        ["🌍 Todos los países"] = "🌍 Todos os países",
        ["📅 Todas las épocas"] = "📅 Todas as épocas",
        ["✕ Limpiar"] = "✕ Limpar",
        ["No hay jugadores con ese filtro."] = "Nenhum jogador com esse filtro.",
        ["Tu plantel está vacío. Andá a Comprar para fichar."] = "Seu elenco está vazio. Vá em Comprar para contratar.",
        ["Mi equipo"] = "Meu elenco",
        ["No tenés jugadores todavía."] = "Você ainda não tem jogadores.",
        ["💰 Ir al mercado"] = "💰 Ir ao mercado",
        ["Nombre del club"] = "Nome do clube",
        ["Nombre de tu equipo"] = "Nome do seu time",
        ["Formación"] = "Formação",
        ["Estilo"] = "Estilo",
        ["Defensivo"] = "Defensivo",
        ["Equilibrado"] = "Equilibrado",
        ["Ofensivo"] = "Ofensivo",
        ["Fuerza"] = "Força",
        ["⚡ Auto XI"] = "⚡ Auto XI",
        ["✓ XI TITULAR COMPLETO — LISTO PARA JUGAR"] = "✓ XI TITULAR COMPLETO — PRONTO PARA JOGAR",

        // ---- concentração ----
        ["🛌 Concentración"] = "🛌 Concentração",
        ["Mandalos a concentrar y en 1 minuto vuelven enteros. Mientras descansan no pueden jugar: ese es el precio."]
            = "Mande-os para a concentração e em 1 minuto voltam a 100%. Enquanto descansam não podem jogar: esse é o preço.",
        ["😴 Que descansen todos"] = "😴 Que descansem todos",
        ["Están todos enteros. A jugar."] = "Estão todos inteiros. Bora jogar.",
        ["Descansar"] = "Descansar",

        // ---- caixas surpresa ----
        ["🎁 Cajas"] = "🎁 Caixas",
        ["Caja Básica"] = "Caixa Básica",
        ["Caja de Plata"] = "Caixa de Prata",
        ["Caja de Oro"] = "Caixa de Ouro",
        ["Caja de Leyenda"] = "Caixa de Lenda",
        ["Caja Élite"] = "Caixa Elite",
        ["Piso 90. Acá no hay relleno."] = "Piso 90. Aqui não tem enchimento.",
        ["📖 Catálogo"] = "📖 Catálogo",
        ["Todos los jugadores que existen, tengas o no. Los de 100+ son versiones PRIME: no se compran, solo salen de las cajas."]
            = "Todos os jogadores que existem no jogo, tendo ou não. Toque em um para ver a ficha completa.",
        ["Lo tenés"] = "Você tem",
        ["Ver más"] = "Ver mais",
        ["Solo por caja"] = "Só na caixa",
        ["🏟️ Estadio"] = "🏟️ Estádio",
        ["Cuanta más gente entra al estadio, más se recauda en cada partido. La entrada se cobra sola al terminar el partido."] = "Quanto mais gente cabe no estádio, mais se arrecada em cada partida. A bilheteria é cobrada sozinha ao terminar o jogo.",
        ["Tu estadio"] = "Seu estádio",
        ["por partido"] = "por partida",
        ["El tuyo"] = "O seu",
        ["Superado"] = "Superado",
        ["Comprar"] = "Comprar",
        ["de recaudación"] = "de bilheteria",
        ["Tribuna Popular"] = "Arquibancada Popular",
        ["La cancha del barrio. Con lo que entra apenas se pagan los focos."] = "O campo do bairro. A renda mal paga os refletores.",
        ["Estadio Municipal"] = "Estádio Municipal",
        ["Tablones de verdad y una popular que empuja."] = "Arquibancada de verdade e uma torcida que empurra.",
        ["Estadio de Ciudad"] = "Estádio da Cidade",
        ["Ya se agotan las entradas una semana antes."] = "Os ingressos esgotam uma semana antes.",
        ["Monumental"] = "Monumental",
        ["Tres bandejas. El rival entra intimidado."] = "Três anéis. O rival entra intimidado.",
        ["Coloso"] = "Colosso",
        ["De los que salen en la tele del mundo entero."] = "Daqueles que aparecem na TV do mundo inteiro.",
        ["Templo del Fútbol"] = "Templo do Futebol",
        ["El estadio más grande que se puede tener. Se llena solo."] = "O maior estádio que se pode ter. Enche sozinho.",
        ["Suspendido"] = "Suspenso",
        ["Suspendido: no puede jugar"] = "Suspenso: não pode jogar",
        ["⬆️ Fusiones disponibles"] = "⬆️ Fusões disponíveis",
        ["Tenés la versión común de estos jugadores. Sacrificala y su versión prime sube un punto."] = "Você tem a versão comum destes jogadores. Sacrifique-a e o prime sobe um ponto.",
        ["Se pierde"] = "Você perde",
        ["🎨 Camiseta y estadio"] = "🎨 Camisa e estádio",
        ["Colores del club"] = "Cores do clube",
        ["Principal"] = "Principal",
        ["Secundario"] = "Secundário",
        ["Gradas"] = "Arquibancadas",
        ["Clásica"] = "Clássica",
        ["Tribuna llena en el color del club."] = "Arquibancada lotada na cor do clube.",
        ["Bicolor"] = "Bicolor",
        ["Franjas alternadas con los dos colores."] = "Faixas alternadas com as duas cores.",
        ["Mosaico"] = "Mosaico",
        ["El clásico mosaico de la hinchada."] = "O clássico mosaico da torcida.",
        ["Nocturna"] = "Noturna",
        ["Estadio a oscuras con celulares prendidos."] = "Estádio no escuro com celulares acesos.",
        ["Vacía"] = "Vazia",
        ["A puertas cerradas, sin público."] = "De portões fechados, sem público.",

        // ---- QR, creditos e legais ----
        ["Escaneá para unirte a la sala"] = "Escaneie para entrar na sala",
        ["Escaneá el QR con el teléfono y entrás directo a la sala."] = "Escaneie o QR com o celular e entre direto na sala.",
        ["📋 Copiar link"] = "📋 Copiar link",
        ["✓ Copiado"] = "✓ Copiado",
        ["Creado por"] = "Criado por",
        ["Créditos, términos y privacidad"] = "Créditos, termos e privacidade",
        ["Créditos"] = "Créditos",
        ["Juego web tipo manager de fútbol."] = "Jogo web estilo manager de futebol.",
        ["Creador y desarrollo"] = "Criador e desenvolvimento",
        ["Creador y diseño de juego"] = "Criador e design de jogo",
        ["Los nombres de futbolistas y selecciones son datos históricos de dominio público; las fuerzas y atributos son una valoración propia para el juego y no representan datos oficiales de ninguna liga, club ni federación."] = "Os nomes de jogadores e seleções são dados históricos de domínio público; as forças e atributos são uma avaliação própria para o jogo e não representam dados oficiais de nenhuma liga, clube ou federação.",
        ["Términos y condiciones"] = "Termos e condições",
        ["1. Qué es esto."] = "1. O que é isto.",
        ["Once de Oro es un juego gratuito, sin fines comerciales y sin dinero real. Toda la moneda del juego es ficticia: no se compra, no se vende y no tiene ningún valor fuera del juego."] = "Once de Oro é um jogo gratuito, sem fins comerciais e sem dinheiro real. Toda a moeda do jogo é fictícia: não se compra, não se vende e não tem valor fora do jogo.",
        ["2. Las cajas sorpresa no se pagan."] = "2. As caixas nunca são pagas.",
        ["Las cajas se abren únicamente con moneda del juego que se gana jugando. No existe ninguna forma de comprarlas con dinero real ni de convertir nada del juego en dinero."] = "As caixas são abertas apenas com moeda do jogo ganha jogando. Não há forma de comprá-las com dinheiro real nem de converter nada do jogo em dinheiro.",
        ["3. Uso razonable."] = "3. Uso justo.",
        ["Pedimos no intentar alterar el juego para perjudicar a otros jugadores en las salas online, ni usar el servicio para enviar contenido ofensivo en los nombres de equipo o de jugador."] = "Pedimos que não altere o jogo para prejudicar outros jogadores nas salas online, nem use nomes de time ou jogador para enviar conteúdo ofensivo.",
        ["4. Sin garantías."] = "4. Sem garantias.",
        ["El juego se ofrece tal como está. Puede tener errores, cambiar o dejar de estar disponible en cualquier momento. No nos hacemos responsables por la pérdida de una partida o de su progreso."] = "O jogo é oferecido como está. Pode ter erros, mudar ou deixar de estar disponível a qualquer momento. Não nos responsabilizamos pela perda de um save ou do seu progresso.",
        ["5. Licencia del código."] = "5. Licença do código.",
        ["El código es público y se distribuye bajo una licencia que permite verlo, aprender de él y compartir mejoras, pero no usarlo con fines comerciales."] = "O código é público sob uma licença que permite vê-lo, aprender com ele e compartilhar melhorias, mas não usá-lo comercialmente.",
        ["Política de privacidad"] = "Política de privacidade",
        ["Qué se guarda en tu dispositivo."] = "O que fica no seu dispositivo.",
        ["Tu partida (equipo, dinero, torneos y estadísticas) y el idioma elegido se guardan en el almacenamiento local de tu navegador. Si borrás los datos del navegador, esa partida se pierde."] = "Seu save (time, dinheiro, torneios e estatísticas) e o idioma escolhido ficam no armazenamento local do navegador. Se apagar os dados do navegador, esse save se perde.",
        ["Qué se guarda en el servidor."] = "O que fica no servidor.",
        ["Sólo si te registrás: tu correo, una versión cifrada de tu contraseña (nunca la contraseña en sí) y tu partida, para que puedas seguirla desde otro dispositivo. Nada más."] = "Só se você se registrar: seu e-mail, uma versão criptografada da sua senha (nunca a senha em si) e seu save, para continuar em outro dispositivo. Nada mais.",
        ["Salas online."] = "Salas online.",
        ["Mientras jugás una sala se comparte con los demás participantes tu nombre de equipo y los jugadores de tu once. La sala vive en memoria y desaparece cuando todos se van: no queda registro del partido."] = "Enquanto joga uma sala, seu nome de time e seu onze inicial são compartilhados com os demais participantes. A sala vive na memória e some quando todos saem: não fica registro da partida.",
        ["Qué NO hacemos."] = "O que NÃO fazemos.",
        ["No hay publicidad, no hay rastreadores de terceros, no se vende ni se comparte ningún dato con nadie, y no se piden datos de pago porque no hay nada que pagar."] = "Sem publicidade, sem rastreadores de terceiros, nenhum dado vendido ou compartilhado, e nunca pedimos dados de pagamento porque não há nada a pagar.",
        ["Menores de edad."] = "Menores de idade.",
        ["El juego es apto para todo público y no pide más datos que un correo opcional para guardar la partida."] = "O jogo é para todos os públicos e não pede mais dados que um e-mail opcional para salvar o progresso.",
        ["Borrar tus datos."] = "Apagar seus dados.",
        ["Podés borrar la partida local desde Inicio con “Reiniciar carrera”. Si te registraste y querés que borremos tu cuenta del servidor, escribinos y la eliminamos."] = "Você pode apagar o save local em Início com “Reiniciar carreira”. Se você se registrou e quer a conta apagada do servidor, escreva para nós e removemos.",
        ["Contacto:"] = "Contato:",
        ["Tu rival ya fichó a"] = "Seu rival já contratou",
        ["No pueden jugar los dos con la misma carta, así que tu equipo se armó sin ellos."] = "Vocês não podem jogar com a mesma carta, então seu XI foi montado sem eles.",
        ["Podés sacrificar a"] = "Você pode sacrificar",
        ["para que este suba a"] = "para que este suba para",
        ["Mejorar"] = "Melhorar",
        ["Ya lo mejoraste. Se puede una sola vez por jugador."] = "Já foi melhorado. Só uma vez por jogador.",
        ["Conseguí a"] = "Consiga",
        ["en el mercado y lo podés sacrificar para subirle un punto a este."] = "no mercado e sacrifique-o para dar +1 a este.",
        ["Caja Olimpo"] = "Caixa Olimpo",
        ["Sólo dioses: del 100 para arriba, garantizado."] = "Só deuses: do 100 para cima, garantido.",
        ["Caja del Payaso"] = "Caixa do Palhaço",
        ["Casi siempre un relleno. Casi."] = "Quase sempre um reserva. Quase.",
        ["El termino medio: sale un titular decente."] = "O meio-termo: sai um titular decente.",
        ["Acá ya se sueña con una figura."] = "Aqui já se sonha com um craque.",
        ["Cara como pocas cosas. Y todavía puede salirte un 79."] = "Cara como poucas coisas. E ainda pode sair um 79.",
        ["GARANTIZADO: un jugador de 110. Palabra de payaso."] = "GARANTIDO: um jogador de 110. Palavra de palhaço.",
        ["Abrir"] = "Abrir",
        ["Listo"] = "Pronto",
        ["Salió de la caja"] = "Saiu da caixa",
        ["¡GARANTIZADO!"] = "GARANTIDO!",
        ["¡SE ROMPIÓ LA CAJA!"] = "A CAIXA QUEBROU!",
        ["Girando…"] = "Girando…",
        ["¡FUERA DE ESCALA!"] = "FORA DE ESCALA!",
        ["Un 110 de verdad. Lástima que juegue como un 45."] = "Um 110 de verdade. Pena que joga como um 45.",
        ["Pagás, tirás la moneda y sale lo que sale. Ojo: lo que salga de una caja se revende a precio de saldo, así que no es negocio abrirlas para vender."]
            = "Você paga, joga a moeda e sai o que sair. Atenção: o que sai de uma caixa é revendido a preço de banana, então não vale a pena abrir para vender.",
        ["Cotiza 110 y remata como nadie, pero adentro de la cancha rinde como un 45. Te vendieron humo."]
            = "Vale 110 e chuta como ninguém, mas dentro de campo rende como um 45. Te venderam fumaça.",
        ["Plantel"] = "Elenco",
        ["de cantera cubren los huecos — igual podés jugar"] = "da base cobrem as lacunas — você pode jogar mesmo assim",
        ["tocá para poner/sacar del XI"] = "toque para colocar/tirar do XI",
        ["Cantera"] = "Base",
        ["libre"] = "livre",
        ["Competiciones"] = "Competições",
        ["Torneo en curso"] = "Torneio em andamento",
        ["▶ Continuar"] = "▶ Continuar",
        ["Inscribirse"] = "Inscrever-se",
        ["Gratis"] = "Grátis",
        ["Tu fuerza"] = "Sua força",
        ["Premio campeón"] = "Prêmio campeão",
        ["Inscripción"] = "Inscrição",
        ["Nivel"] = "Nível",
        ["⚠️ Necesitás un XI válido (11 titulares según tu formación) para inscribirte."] = "⚠️ Você precisa de um XI válido (11 titulares para sua formação) para se inscrever.",
        ["Armar equipo"] = "Montar time",
        ["Ir al mercado"] = "Ir ao mercado",
        ["Rec."] = "Rec.",
        ["Tu XI tiene juveniles de cantera cubriendo huecos. Podés competir igual, pero fichá refuerzos para rendir mejor."]
            = "Seu XI tem jogadores de base preenchendo lacunas. Você pode competir mesmo assim, mas contrate reforços para render mais.",
        ["Tu equipo está por debajo del nivel — ganá plata en torneos menores y reforzá antes."]
            = "Seu time está abaixo do nível — ganhe dinheiro em torneios menores e reforce antes.",
        ["Copa Regional"] = "Copa Regional",
        ["Copa América"] = "Copa América",
        ["Champions League"] = "Champions League",
        ["Copa del Mundo"] = "Copa do Mundo",
        ["El primer trofeo · rivales accesibles"] = "O primeiro troféu · rivais acessíveis",
        ["El continente sudamericano en juego"] = "O continente sul-americano em jogo",
        ["La élite europea bajo las luces"] = "A elite europeia sob as luzes",
        ["La cima · aquí se forja el 7–0 perfecto"] = "O topo · aqui se forja o 7–0 perfeito",
        ["Fase de grupos · Jornada {0}"] = "Fase de grupos · Rodada {0}",
        ["Fecha {0} de {1}"] = "Rodada {0} de {1}",
        ["Ligas nacionales"] = "Ligas nacionais",
        ["Copas nacionales"] = "Copas nacionais",
        ["Torneos continentales"] = "Torneios continentais",
        ["Selecciones"] = "Seleções",
        ["Liga · todos contra todos"] = "Liga · pontos corridos",
        ["Eliminación directa"] = "Mata-mata",
        ["Grupos + eliminatorias"] = "Grupos + mata-mata",
        ["Tabla de posiciones"] = "Tabela de classificação",
        ["Temporada terminada"] = "Temporada encerrada",
        ["Fichado"] = "Contratado",
        ["Carrera real"] = "Carreira real",
        ["Partidos con su selección"] = "Jogos pela seleção",
        ["Goles con su selección"] = "Gols pela seleção",
        ["Mundiales"] = "Copas do Mundo",
        ["Balón de Oro"] = "Bola de Ouro",
        ["Copas de Europa"] = "Copas da Europa",
        ["Campeón del Mundo en"] = "Campeão do mundo em",
        ["finales perdidas"] = "finais perdidas",
        ["Cualidades dentro del juego, derivadas de su fuerza."] = "Qualidades dentro do jogo, derivadas da sua força.",
        ["Atributos"] = "Atributos",
        ["No está en tu equipo. Fichalo para verlo rendir y llevarle las estadísticas."]
            = "Ele não está no seu elenco. Contrate-o para vê-lo render e acompanhar suas estatísticas.",
        ["Reflejos"] = "Reflexos",
        ["Achique"] = "Saída do gol",
        ["Manos"] = "Domínio de bola",
        ["Juego aéreo"] = "Jogo aéreo",
        ["Distribución"] = "Distribuição",
        ["Marca"] = "Marcação",
        ["Quite"] = "Desarme",
        ["Fuerza"] = "Força",
        ["Salida"] = "Saída de bola",
        ["Pase"] = "Passe",
        ["Visión"] = "Visão",
        ["Regate"] = "Drible",
        ["Resistencia"] = "Resistência",
        ["Recuperación"] = "Recuperação",
        ["Definición"] = "Finalização",
        ["Velocidad"] = "Velocidade",
        ["Remate"] = "Chute",
        ["Desmarque"] = "Movimentação",
        ["Época"] = "Era",
        ["Estado físico"] = "Condição física",
        ["Lesionado"] = "Lesionado",
        ["Lesionado: no puede jugar"] = "Lesionado: não pode jogar",
        ["Sacar del XI"] = "Tirar do XI",
        ["Poner en el XI"] = "Colocar no XI",
        ["Disponible"] = "Disponível",
        ["partido"] = "jogo",
        ["partidos"] = "jogos",
        ["Cansancio"] = "Cansaço",
        ["de fuerza"] = "de força",
        ["Descansa cuando no juega. Jugar fundido aumenta el riesgo de lesión."]
            = "Ele descansa quando não joga. Jogar esgotado aumenta o risco de lesão.",
        ["Con tu equipo"] = "Com seu time",
        ["Goles"] = "Gols",
        ["Lesiones"] = "Lesões",
        ["Goles/partido"] = "Gols/jogo",
        ["Copa juvenil"] = "Copa juvenil",
        ["Sonido"] = "Som",
        ["Torneos de formación para tu cantera: cuestan plata y NO dan premio. Lo que ganás es experiencia. No cansan ni lesionan."] = "Torneios de formação para a sua base: custam dinheiro e NÃO pagam prêmio. O que você ganha é experiência. Não cansam nem lesionam.",
        ["por jugar"] = "por jogar",
        ["a cada juvenil"] = "para cada juvenil",
        ["Necesitás al menos 5 juveniles. Creá jugadores o fichá promesas con un ojeador."] = "Você precisa de pelo menos 5 juvenis. Crie jogadores ou contrate promessas com um olheiro.",
        ["Elegí 5 juveniles"] = "Escolha 5 juvenis",
        ["Rival"] = "Rival",
        ["por victoria"] = "por vitória",
        ["Jugar"] = "Jogar",
        ["Jugar · Gratis"] = "Jogar · Grátis",
        ["ganados"] = "vitórias",
        ["¡INVICTOS!"] = "INVICTOS!",
        ["Tu cantera"] = "Sua base",
        ["Copa Barrial"] = "Copa do Bairro",
        ["Torneo Sub-19"] = "Torneio Sub-19",
        ["Copa Federal Juvenil"] = "Copa Nacional Juvenil",
        ["Mundialito Juvenil"] = "Mundialito Juvenil",
        ["Potreros del barrio. Entrada libre, ideal para empezar."] = "Campinhos do bairro. Entrada livre, ideal para começar.",
        ["Categorías juveniles federadas. Ya se juega en serio."] = "Categorias de base federadas. Já se joga a sério.",
        ["Lo mejor de las inferiores del país."] = "O melhor das categorias de base do país.",
        ["El torneo donde se miran todos los ojeadores del mundo."] = "O torneio que todos os olheiros do mundo assistem.",
        ["Ojeadores"] = "Olheiros",
        ["Techo"] = "Teto",
        ["Mejoras"] = "Melhorias",
        ["Contratar un ojeador"] = "Contratar um olheiro",
        ["Los ojeadores buscan jóvenes promesas. Lo que pagás no es lo que rinden hoy, sino hasta dónde pueden llegar."] = "Os olheiros procuram jovens promessas. Você não paga pelo que eles são hoje, mas por até onde podem chegar.",
        ["Techo de las promesas"] = "Teto das promessas",
        ["Buscar"] = "Buscar",
        ["Todavía no encontraste promesas. Contratá un ojeador."] = "Ainda não encontrou promessas. Contrate um olheiro.",
        ["Promesas encontradas"] = "Promessas encontradas",
        ["años"] = "anos",
        ["Hoy"] = "Hoje",
        ["Puede llegar a"] = "Pode chegar a",
        ["Fichar"] = "Contratar",
        ["Ojeador local"] = "Olheiro local",
        ["Ojeador regional"] = "Olheiro regional",
        ["Ojeador internacional"] = "Olheiro internacional",
        ["Ojeador de élite"] = "Olheiro de elite",
        ["Recorre canchas de barrio. Encuentra chicos aprovechables."] = "Percorre campos de várzea. Encontra garotos aproveitáveis.",
        ["Cubre todo el país. Aparecen los primeros nombres serios."] = "Cobre o país inteiro. Surgem os primeiros nomes sérios.",
        ["Viaja por el continente. Promesas de selección juvenil."] = "Viaja pelo continente. Promessas de seleção de base.",
        ["La red que descubre a los cracks antes que nadie."] = "A rede que descobre os craques antes de todos.",
        ["Tokens de mejora"] = "Tokens de melhoria",
        ["Sirven para subir de nivel a cualquier jugador tuyo, hasta 99."] = "Servem para subir de nível qualquer jogador seu, até 99.",
        ["Cuanto más fuerte es el jugador, más tokens cuesta cada punto. Así mejorar a una estrella es una inversión de verdad."] = "Quanto mais forte o jogador, mais tokens custa cada ponto. Melhorar um craque é um investimento de verdade.",
        ["Academia"] = "Academia",
        ["Creá tus propios jugadores y hacelos crecer entrenando y jugando. Entrenar cuesta cada vez más caro: es donde tu fortuna encuentra destino."]
            = "Crie seus próprios jogadores e faça-os crescer treinando e jogando. Treinar fica mais caro a cada nível: é onde a sua fortuna finalmente tem destino.",
        ["Nombre"] = "Nome",
        ["Tu joya"] = "Sua joia",
        ["País"] = "País",
        ["Puesto"] = "Posição",
        ["Costo"] = "Custo",
        ["arranca en"] = "começa em",
        ["＋ Crear jugador"] = "＋ Criar jogador",
        ["No te alcanza la plata para crear un jugador."] = "Você não tem dinheiro para criar um jogador.",
        ["Todavía no creaste ningún jugador."] = "Você ainda não criou nenhum jogador.",
        ["Tus jugadores"] = "Seus jogadores",
        ["Entrenar"] = "Treinar",
        ["Vender"] = "Vender",
        ["Máximo"] = "Máximo",
        ["entrenos"] = "treinos",
        ["Ruta de avances"] = "Rota de evolução",
        ["Rivales"] = "Rivais",
        ["Los rivales se refuerzan con tu trayectoria y tu nivel"] = "Os rivais ficam mais fortes com sua trajetória e seu nível",
        ["Juvenil"] = "Base",
        ["Promesa"] = "Promessa",
        ["Titular"] = "Titular",
        ["Figura"] = "Destaque",
        ["Crack"] = "Craque",
        ["Leyenda"] = "Lenda",

        ["Liga Argentina"] = "Campeonato Argentino",
        ["Copa Argentina"] = "Copa Argentina",
        ["Copa del Rey"] = "Copa del Rey",
        ["Copa Libertadores"] = "Copa Libertadores",
        ["Eurocopa"] = "Eurocopa",
        ["Temporada completa en el fútbol argentino"] = "Temporada completa no futebol argentino",
        ["El campeonato más físico de Sudamérica"] = "O campeonato mais físico da América do Sul",
        ["Técnica y posesión al máximo nivel"] = "Técnica e posse no mais alto nível",
        ["La liga más competitiva del mundo"] = "A liga mais competitiva do mundo",
        ["Eliminación directa: no se perdona nada"] = "Mata-mata: não perdoa nada",
        ["El torneo de las sorpresas"] = "O torneio das surpresas",
        ["La copa más antigua del fútbol"] = "A copa mais antiga do futebol",
        ["La gloria eterna de Sudamérica"] = "A glória eterna da América do Sul",
        ["El camino alternativo a la gloria europea"] = "O caminho alternativo para a glória europeia",
        ["El torneo de selecciones más parejo"] = "O torneio de seleções mais equilibrado",
        ["OCTAVOS DE FINAL"] = "OITAVAS DE FINAL",
        ["CUARTOS DE FINAL"] = "QUARTAS DE FINAL",
        ["SEMIFINAL"] = "SEMIFINAL",
        ["LA FINAL"] = "A FINAL",
        ["No hay ningún torneo en curso."] = "Não há nenhum torneio em andamento.",
        ["Elegir torneo"] = "Escolher torneio",
        ["PREVIA"] = "PRÉVIA",
        ["📊 Pronóstico"] = "📊 Prognóstico",
        ["goles esperados"] = "gols esperados",
        ["favoritismo"] = "favoritismo",
        ["Marcadores más probables:"] = "Placares mais prováveis:",
        ["Ganás"] = "Vitória",
        ["Perdés"] = "Derrota",
        ["Empate"] = "Empate",
        ["▶ Ver el partido"] = "▶ Assistir a partida",
        ["FINAL"] = "FIM DE JOGO",
        ["PENALES"] = "PÊNALTIS",
        ["Recorrido en la"] = "Sua caminhada na",
        ["¡VICTORIA!"] = "VITÓRIA!",
        ["EMPATE"] = "EMPATE",
        ["DERROTA"] = "DERROTA",
        ["en premios"] = "em prêmios",
        ["¡CAMPEÓN!"] = "CAMPEÃO!",
        ["Cobrar y volver"] = "Receber e voltar",
        ["Volver al mercado"] = "Voltar ao mercado",
        ["Volver"] = "Voltar",
        ["Reforzá el equipo y volvé más fuerte."] = "Reforce o time e volte mais forte.",
        ["Posesión"] = "Posse",
        ["Remates"] = "Finalizações",
        ["Faltas"] = "Faltas",
        ["⏩ Saltar al final"] = "⏩ Pular para o fim",
        ["1º TIEMPO"] = "1º TEMPO",
        ["ENTRETIEMPO"] = "INTERVALO",
        ["2º TIEMPO"] = "2º TEMPO",
        ["PRÓRROGA 1"] = "PRORROGAÇÃO 1",
        ["PRÓRROGA 2"] = "PRORROGAÇÃO 2",
        ["TANDA DE PENALES"] = "DISPUTA DE PÊNALTIS",
        // Relato do jogo (modelos com {0}/{1} = nomes/time, não se traduzem)
        ["¡Comienza el partido!"] = "Começa a partida!",
        ["Falta de {0} sobre {1}"] = "Falta de {0} sobre {1}",
        ["Amarilla a {0}"] = "Amarelo para {0}",
        ["Roja a {0}"] = "Vermelho para {0}",
        ["{0} queda golpeado y necesita atención"] = "{0} fica caído e precisa de atendimento",
        ["Offside · posición adelantada de {0}"] = "Impedimento · {0} estava adiantado",
        ["Remate de {0} ({1})"] = "Finalização de {0} ({1})",
        ["¡GOOOL de {0}!"] = "GOOOL de {0}!",
        ["¡Atajó {0}!"] = "{0} defende!",
        ["¡{0} al palo!"] = "{0} na trave!",
        ["Remate desviado de {0}"] = "Finalização para fora de {0}",
        ["Pausa de hidratación (min {0})"] = "Pausa para hidratação (min {0})",
        ["Entretiempo"] = "Intervalo",
        ["Arranca el segundo tiempo"] = "Começa o segundo tempo",
        ["Final del partido"] = "Fim de jogo",
        ["¡Tiempo suplementario!"] = "Prorrogação!",
        ["¡Definición por penales!"] = "Vai para os pênaltis!",
        ["{0} anota"] = "{0} converte",
        ["{0} le ataja a {1}"] = "{0} defende de {1}",
        ["Duelo online · jugá contra amigos"] = "Duelo online · jogue contra amigos",
        ["Crear una sala"] = "Criar uma sala",
        ["Unirse a una sala"] = "Entrar em uma sala",
        ["Tu nombre"] = "Seu nome",
        ["Tu apodo"] = "Seu apelido",
        ["Equipos"] = "Times",
        ["Draft parejo"] = "Draft justo",
        ["Equipo de carrera"] = "Time de carreira",
        ["Formato"] = "Formato",
        ["Único"] = "Único",
        ["Mejor de 3"] = "Melhor de 3",
        ["Mini-torneo"] = "Mini-torneio",
        ["🌐 Crear sala"] = "🌐 Criar sala",
        ["Código de sala"] = "Código da sala",
        ["Entrar"] = "Entrar",
        ["Jugadores"] = "Jogadores",
        ["Presupuesto por jugador:"] = "Orçamento por jogador:",
        ["Pedile el código de 4 letras a tu amigo que creó la sala."] = "Peça o código de 4 letras ao amigo que criou a sala.",
        ["TÚ"] = "VOCÊ",
        ["👑 Anfitrión"] = "👑 Anfitrião",
        ["Invitado"] = "Convidado",
        ["▶ Empezar"] = "▶ Começar",
        ["Esperando que se una al menos un amigo…"] = "Aguardando pelo menos um amigo entrar com o código",
        ["Esperando que el anfitrión inicie la partida…"] = "Aguardando o anfitrião iniciar a partida…",
        ["¡Equipo listo!"] = "Time pronto!",
        ["Esperando al resto…"] = "Aguardando os demais…",
        ["(vos)"] = "(você)",
        ["LISTO ✓"] = "PRONTO ✓",
        ["armando…"] = "montando…",
        ["Tu equipo de carrera"] = "Seu time de carreira",
        ["✓ Usar este equipo y estar listo"] = "✓ Usar este time e ficar pronto",
        ["Serie:"] = "Série:",
        ["¡GANASTE!"] = "VOCÊ VENCEU!",
        ["PERDISTE"] = "VOCÊ PERDEU",
        ["gana"] = "vence",
        ["gana la contienda online."] = "vence a disputa online.",
        ["MINUTO"] = "MINUTO",
        ["Partido"] = "Partida",
        ["Partido único"] = "Partida única",
        ["Página no encontrada"] = "Página não encontrada",
        ["FUERA DE JUEGO"] = "IMPEDIMENTO",
        ["La página que buscás no existe."] = "A página que você procura não existe.",
        ["Volver al inicio"] = "Voltar ao início",
        ["Tu cuenta"] = "Sua conta",
        ["Guardar progreso"] = "Salvar progresso",
        ["Guardá tu progreso"] = "Salve seu progresso",
        ["Este servidor todavía no tiene cuentas habilitadas. Tu progreso se guarda en este navegador."]
            = "Este servidor ainda não tem contas habilitadas. Seu progresso é salvo neste navegador.",
        ["☁ Progreso guardado"] = "☁ Progresso salvo",
        ["Tu equipo, tu dinero, los torneos y todas tus estadísticas se guardan en tu cuenta y te siguen a cualquier dispositivo."]
            = "Seu time, seu dinheiro, os torneios e todas as suas estatísticas ficam salvos na sua conta e te acompanham em qualquer dispositivo.",
        ["☁ Guardar ahora"] = "☁ Salvar agora",
        ["✓ Guardado"] = "✓ Salvo",
        ["Cerrar sesión"] = "Sair",
        ["Crear cuenta"] = "Criar conta",
        ["Creá tu cuenta y todo lo que ya jugaste (equipo, dinero, torneos y estadísticas) se guarda ahí mismo. No perdés nada."]
            = "Crie sua conta e tudo o que você já jogou (time, dinheiro, torneios e estatísticas) fica salvo ali mesmo. Você não perde nada.",
        ["Entrá para recuperar tu equipo y seguir donde lo dejaste."] = "Entre para recuperar seu time e continuar de onde parou.",
        ["Nombre de manager"] = "Nome de técnico",
        ["Email"] = "Email",
        ["Contraseña"] = "Senha",
        ["Mínimo 6 caracteres"] = "Mínimo 6 caracteres",
        ["Un momento…"] = "Um momento…",
        ["Crear cuenta y guardar mi progreso"] = "Criar conta e salvar meu progresso",
    };
}
